- name: Add Docker GPG apt Key
  become: true
  ansible.builtin.apt_key:
    url: https://nvidia.github.io/libnvidia-container/gpgkey
    state: present

- name: Get deb expression
  ansible.builtin.shell: |
    distribution=$(. /etc/os-release;echo $ID$VERSION_ID) \
      && curl -s -L https://nvidia.github.io/libnvidia-container/$distribution/libnvidia-container.list
  register: deb

- debug:
    msg: '{{ deb.stdout }}'

- name: Add Nvidia Container Repository
  become: true
  ansible.builtin.apt_repository:
    repo: '{{ deb.stdout }}'
    state: present

- name: Update apt and install nvidia-docker
  become: true
  ansible.builtin.apt:
    name:
      - nvidia-docker2
    state: present
    update_cache: true

- name: Restart docker daemon
  become: true
  ansible.builtin.service:
    name: docker
    state: restarted
